### ISSUE TITLE
Make the quotes tweetable

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-css#36]
Hovering on the quotes should display a "Tweet this" button with the quote embedded and a cc of the author

**Comment by JulieAlgolia** [comment]
“What was I thinking putting CSS in JS? I see now that building pure-CSS apps is the future!” @ vJeux
https://www.algolia.com/css

“The only thing better than a static website is a static search engine.” @ smashingmag
https://www.algolia.com/css

“Javascript is dead.” @ chriscoyier
https://www.algolia.com/css

“This is the best thing that happened since sliced bread.” @ porteneuve
https://www.algolia.com/css

“With Algolia, we can finally deliver an entire search experience inside of your inbox.” @ Nico_g
https://www.algolia.com/css

“Given the success of this project, we’re now eagerly awaiting Algolia’s CSS Popup and CSS Ad Tracking APIs.” @ SachaGreif
https://www.algolia.com/css

**Comment by Haroenv** [comment]
last one is 5 characters too much @JulieAlgolia

**Comment by LukyVj** [comment]
I can definitely check if the quote is too long, I replace the last chars by `…`

**Comment by Haroenv** [comment]
Well since it's just 5 characters, you might get there by removing an enter, the quote characters?

**Comment by JulieAlgolia** [comment]
I have another one guys! I updated it. Thank you @Haroenv for noticing.
